//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GETweetsWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class DummyTweet
    {
        public int LocalId { get; set; }
        public System.DateTime TweetDate { get; set; }
        public int Sentiment { get; set; }
        public string PoliticalParty { get; set; }
        public int GeoShapeId { get; set; }
    
        public virtual GeoShape GeoShape { get; set; }
    }
}
