//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GETweetsWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeoShape
    {
        public GeoShape()
        {
            this.VoteMaps = new HashSet<VoteMap>();
            this.VoteSentiments = new HashSet<VoteSentiment>();
            this.VoteTrends = new HashSet<VoteTrend>();
        }
    
        public int GeoShapeId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<VoteMap> VoteMaps { get; set; }
        public virtual ICollection<VoteSentiment> VoteSentiments { get; set; }
        public virtual ICollection<VoteTrend> VoteTrends { get; set; }
    }
}
