//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GETweetsWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GETweetsWebDB : DbContext
    {
        public GETweetsWebDB()
            : base("name=GETweetsWebDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GeoShape> GeoShapes { get; set; }
        public virtual DbSet<VoteMap> VoteMaps { get; set; }
        public virtual DbSet<VoteSentiment> VoteSentiments { get; set; }
        public virtual DbSet<VoteTrend> VoteTrends { get; set; }
    }
}
