//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GETweetsWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoteMap
    {
        public int VoteMapId { get; set; }
        public string Party { get; set; }
        public Nullable<decimal> WinningDiff { get; set; }
        public Nullable<int> GeoShapeId { get; set; }
    
        public virtual GeoShape GeoShape { get; set; }
    }
}
